-- Vehicle Rental System - SQL Queries and Solutions
-- This file contains various SQL queries demonstrating database operations

-- ============================================================================
-- BASIC QUERIES (CRUD Operations)
-- ============================================================================

-- Query 1: Retrieve all available vehicles
-- Purpose: List all vehicles that are currently available for rent
SELECT 
    v.vehicle_id,
    v.make,
    v.model,
    v.year,
    v.license_plate,
    v.color,
    vt.type_name,
    v.daily_rate,
    v.mileage
FROM Vehicles v
JOIN VehicleTypes vt ON v.type_id = vt.type_id
WHERE v.status = 'available'
ORDER BY v.daily_rate;

-- Query 2: Retrieve customer information by email
-- Purpose: Find a specific customer using their email address
SELECT 
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    license_number,
    date_of_birth,
    registration_date
FROM Customers
WHERE email = 'john.doe@email.com';

-- Query 3: Insert a new customer
-- Purpose: Add a new customer to the database
INSERT INTO Customers (first_name, last_name, email, phone, address, license_number, date_of_birth)
VALUES ('Sarah', 'Connor', 'sarah.connor@email.com', '555-0106', '999 Tech Rd, City, State 12345', 'DL678901', '1993-06-20');

-- Query 4: Update vehicle mileage after rental
-- Purpose: Update the mileage of a vehicle after it's returned
UPDATE Vehicles
SET mileage = mileage + 500,
    last_service_date = CURRENT_DATE
WHERE vehicle_id = 1;

-- Query 5: Delete a cancelled rental
-- Purpose: Remove a rental that was cancelled
DELETE FROM Rentals
WHERE rental_id = 6 AND status = 'cancelled';

-- ============================================================================
-- INTERMEDIATE QUERIES (JOINs and Aggregations)
-- ============================================================================

-- Query 6: List all active rentals with customer and vehicle details
-- Purpose: Show currently active rentals with full information
SELECT 
    r.rental_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    c.phone,
    v.make || ' ' || v.model AS vehicle,
    v.license_plate,
    r.rental_date,
    r.expected_return_date,
    r.total_amount,
    CURRENT_DATE - r.rental_date AS days_rented
FROM Rentals r
JOIN Customers c ON r.customer_id = c.customer_id
JOIN Vehicles v ON r.vehicle_id = v.vehicle_id
WHERE r.status = 'active'
ORDER BY r.rental_date DESC;

-- Query 7: Calculate total revenue by vehicle type
-- Purpose: Show revenue generated by each vehicle type
SELECT 
    vt.type_name,
    COUNT(r.rental_id) AS total_rentals,
    SUM(r.total_amount) AS total_revenue,
    AVG(r.total_amount) AS avg_rental_amount
FROM VehicleTypes vt
LEFT JOIN Vehicles v ON vt.type_id = v.type_id
LEFT JOIN Rentals r ON v.vehicle_id = r.vehicle_id AND r.status = 'completed'
GROUP BY vt.type_name
ORDER BY total_revenue DESC NULLS LAST;

-- Query 8: Find customers with multiple rentals
-- Purpose: Identify repeat customers
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    COUNT(r.rental_id) AS rental_count,
    SUM(r.total_amount) AS total_spent
FROM Customers c
JOIN Rentals r ON c.customer_id = r.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email
HAVING COUNT(r.rental_id) > 1
ORDER BY rental_count DESC;

-- Query 9: Calculate average rental duration by vehicle type
-- Purpose: Analyze rental patterns by vehicle type
SELECT 
    vt.type_name,
    COUNT(r.rental_id) AS rental_count,
    AVG(r.expected_return_date - r.rental_date) AS avg_rental_days,
    MIN(r.expected_return_date - r.rental_date) AS min_rental_days,
    MAX(r.expected_return_date - r.rental_date) AS max_rental_days
FROM VehicleTypes vt
JOIN Vehicles v ON vt.type_id = v.type_id
JOIN Rentals r ON v.vehicle_id = r.vehicle_id
WHERE r.status IN ('completed', 'active')
GROUP BY vt.type_name
ORDER BY avg_rental_days DESC;

-- Query 10: List vehicles that need maintenance (high mileage)
-- Purpose: Identify vehicles with mileage over 20,000 miles
SELECT 
    v.vehicle_id,
    v.make,
    v.model,
    v.year,
    v.license_plate,
    v.mileage,
    v.last_service_date,
    CURRENT_DATE - v.last_service_date AS days_since_service
FROM Vehicles v
WHERE v.mileage > 20000
   OR (v.last_service_date IS NOT NULL AND CURRENT_DATE - v.last_service_date > 90)
ORDER BY v.mileage DESC;

-- ============================================================================
-- ADVANCED QUERIES (Subqueries, CTEs, Window Functions)
-- ============================================================================

-- Query 11: Find the most popular vehicle (most rented)
-- Purpose: Identify which vehicle has been rented the most times
WITH VehicleRentalCounts AS (
    SELECT 
        v.vehicle_id,
        v.make,
        v.model,
        v.year,
        v.license_plate,
        COUNT(r.rental_id) AS rental_count
    FROM Vehicles v
    LEFT JOIN Rentals r ON v.vehicle_id = r.vehicle_id
    GROUP BY v.vehicle_id, v.make, v.model, v.year, v.license_plate
)
SELECT 
    vehicle_id,
    make || ' ' || model || ' (' || year || ')' AS vehicle,
    license_plate,
    rental_count
FROM VehicleRentalCounts
WHERE rental_count = (SELECT MAX(rental_count) FROM VehicleRentalCounts);

-- Query 12: Calculate monthly revenue trend
-- Purpose: Show revenue by month for trend analysis
SELECT 
    TO_CHAR(r.rental_date, 'YYYY-MM') AS month,
    COUNT(r.rental_id) AS total_rentals,
    SUM(r.total_amount) AS total_revenue,
    AVG(r.total_amount) AS avg_rental_value
FROM Rentals r
WHERE r.status = 'completed'
GROUP BY TO_CHAR(r.rental_date, 'YYYY-MM')
ORDER BY month DESC;

-- Query 13: Find customers who haven't rented in the last 30 days
-- Purpose: Identify inactive customers for marketing campaigns
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    MAX(r.rental_date) AS last_rental_date,
    CURRENT_DATE - MAX(r.rental_date) AS days_since_last_rental
FROM Customers c
JOIN Rentals r ON c.customer_id = r.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email
HAVING MAX(r.rental_date) < CURRENT_DATE - INTERVAL '30 days'
ORDER BY days_since_last_rental DESC;

-- Query 14: Rank vehicles by revenue within each type
-- Purpose: Identify top performers in each vehicle category
SELECT 
    vt.type_name,
    v.make || ' ' || v.model AS vehicle,
    v.license_plate,
    COALESCE(SUM(r.total_amount), 0) AS total_revenue,
    RANK() OVER (PARTITION BY vt.type_name ORDER BY COALESCE(SUM(r.total_amount), 0) DESC) AS rank_in_type
FROM VehicleTypes vt
JOIN Vehicles v ON vt.type_id = v.type_id
LEFT JOIN Rentals r ON v.vehicle_id = r.vehicle_id AND r.status = 'completed'
GROUP BY vt.type_name, v.vehicle_id, v.make, v.model, v.license_plate
ORDER BY vt.type_name, rank_in_type;

-- Query 15: Find vehicles with overdue rentals
-- Purpose: Identify rentals that are past their expected return date
SELECT 
    r.rental_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.phone,
    v.make || ' ' || v.model AS vehicle,
    v.license_plate,
    r.rental_date,
    r.expected_return_date,
    CURRENT_DATE - r.expected_return_date AS days_overdue,
    r.total_amount
FROM Rentals r
JOIN Customers c ON r.customer_id = c.customer_id
JOIN Vehicles v ON r.vehicle_id = v.vehicle_id
WHERE r.status = 'active' 
  AND r.expected_return_date < CURRENT_DATE
ORDER BY days_overdue DESC;

-- ============================================================================
-- BUSINESS INTELLIGENCE QUERIES
-- ============================================================================

-- Query 16: Customer lifetime value analysis
-- Purpose: Calculate total value of each customer
SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    c.registration_date,
    COUNT(r.rental_id) AS total_rentals,
    SUM(r.total_amount) AS lifetime_value,
    AVG(r.total_amount) AS avg_transaction,
    MAX(r.rental_date) AS last_rental_date
FROM Customers c
LEFT JOIN Rentals r ON c.customer_id = r.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email, c.registration_date
ORDER BY lifetime_value DESC NULLS LAST;

-- Query 17: Vehicle utilization rate
-- Purpose: Calculate how often each vehicle is rented
WITH VehicleStats AS (
    SELECT 
        v.vehicle_id,
        v.make,
        v.model,
        v.license_plate,
        v.purchase_date,
        COUNT(r.rental_id) AS rental_count,
        SUM(r.expected_return_date - r.rental_date) AS total_rental_days,
        CURRENT_DATE - v.purchase_date AS days_in_fleet
    FROM Vehicles v
    LEFT JOIN Rentals r ON v.vehicle_id = r.vehicle_id
    WHERE v.purchase_date IS NOT NULL
    GROUP BY v.vehicle_id, v.make, v.model, v.license_plate, v.purchase_date
)
SELECT 
    vehicle_id,
    make || ' ' || model AS vehicle,
    license_plate,
    rental_count,
    total_rental_days,
    days_in_fleet,
    ROUND((total_rental_days::DECIMAL / days_in_fleet) * 100, 2) AS utilization_percentage
FROM VehicleStats
WHERE days_in_fleet > 0
ORDER BY utilization_percentage DESC;

-- Query 18: Payment method analysis
-- Purpose: Analyze payment preferences
SELECT 
    p.payment_method,
    COUNT(p.payment_id) AS transaction_count,
    SUM(p.amount) AS total_amount,
    AVG(p.amount) AS avg_transaction,
    ROUND((COUNT(p.payment_id)::DECIMAL / (SELECT COUNT(*) FROM Payments)) * 100, 2) AS percentage_of_transactions
FROM Payments p
WHERE p.status = 'completed'
GROUP BY p.payment_method
ORDER BY total_amount DESC;

-- Query 19: Find available vehicles for a specific date range
-- Purpose: Check vehicle availability for booking
SELECT 
    v.vehicle_id,
    v.make || ' ' || v.model AS vehicle,
    vt.type_name,
    v.license_plate,
    v.daily_rate,
    v.mileage
FROM Vehicles v
JOIN VehicleTypes vt ON v.type_id = vt.type_id
WHERE v.status = 'available'
  AND v.vehicle_id NOT IN (
      SELECT vehicle_id
      FROM Rentals
      WHERE status = 'active'
        AND (
            (rental_date <= '2024-12-30' AND expected_return_date >= '2024-12-25')
        )
  )
ORDER BY v.daily_rate;

-- Query 20: Complete rental history with payment information
-- Purpose: Full audit trail of rentals and payments
SELECT 
    r.rental_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    v.make || ' ' || v.model AS vehicle,
    v.license_plate,
    r.rental_date,
    r.return_date,
    r.expected_return_date,
    r.total_amount AS rental_amount,
    r.status AS rental_status,
    p.payment_id,
    p.amount AS payment_amount,
    p.payment_method,
    p.payment_date,
    p.status AS payment_status
FROM Rentals r
JOIN Customers c ON r.customer_id = c.customer_id
JOIN Vehicles v ON r.vehicle_id = v.vehicle_id
LEFT JOIN Payments p ON r.rental_id = p.rental_id
ORDER BY r.rental_date DESC, r.rental_id;

-- ============================================================================
-- DATA INTEGRITY AND MAINTENANCE QUERIES
-- ============================================================================

-- Query 21: Check for data inconsistencies
-- Purpose: Find rentals with mismatched payment amounts
SELECT 
    r.rental_id,
    r.total_amount AS rental_amount,
    SUM(p.amount) AS total_payments,
    r.total_amount - COALESCE(SUM(p.amount), 0) AS difference
FROM Rentals r
LEFT JOIN Payments p ON r.rental_id = p.rental_id AND p.status = 'completed'
WHERE r.status = 'completed'
GROUP BY r.rental_id, r.total_amount
HAVING r.total_amount != COALESCE(SUM(p.amount), 0)
ORDER BY difference DESC;

-- Query 22: Database statistics summary
-- Purpose: Overall system statistics
SELECT 
    (SELECT COUNT(*) FROM Customers) AS total_customers,
    (SELECT COUNT(*) FROM Vehicles) AS total_vehicles,
    (SELECT COUNT(*) FROM Vehicles WHERE status = 'available') AS available_vehicles,
    (SELECT COUNT(*) FROM Rentals WHERE status = 'active') AS active_rentals,
    (SELECT COUNT(*) FROM Rentals WHERE status = 'completed') AS completed_rentals,
    (SELECT COALESCE(SUM(total_amount), 0) FROM Rentals WHERE status = 'completed') AS total_revenue,
    (SELECT COUNT(*) FROM Payments WHERE status = 'completed') AS total_payments;
